[package]
name = "pyannote-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
onnxruntime = "0.0.14"
ort = "1.16.2"
plotters = "0.3.5"
